workflows:
  unity-mac-workflow:
      # Building Unity on macOS requires special instance type which is available upon request
      name: Unity Mac Workflow
      environment:
        groups:
          # Add the group environment variables in Codemagic UI (either in Application/Team variables) - https://docs.codemagic.io/variables/environment-variable-groups/
          - unity # <-- (Includes UNITY_SERIAL, UNITY_USERNAME, UNITY_PASSWORD)
        vars:
          UNITY_BIN: /Applications/Unity/Hub/Editor/2020.3.20f1/Unity.app/Contents/MacOS/Unity
      scripts:
        - name: Activate License
          script: $UNITY_BIN -batchmode -quit -logFile -serial ${UNITY_SERIAL?} -username ${UNITY_USERNAME?} -password ${UNITY_PASSWORD?}
        - name: Run Unit Tests
          script: $UNITY_BIN -batchmode -executeMethod Runner.RunUnitTests -logFile -nographics -projectPath .
        - name: Build
          script: $UNITY_BIN -batchmode -quit -logFile -projectPath . -executeMethod BuildScript.BuildMac -nographics
      artifacts:
        - "Build/UnitTestingPong.app"
      publishing:
        scripts:
          - name: Deactivate License
            script: $UNITY_BIN -batchmode -quit -returnlicense -nographics

  unity-windows-workflow:
      name: Unity Windows Workflow
      instance_type: windows_x2 # This instance type is available to all teams with enabled billing
      environment:
        groups:
          # Add the group environment variables in Codemagic UI (either in Application/Team variables) - https://docs.codemagic.io/variables/environment-variable-groups/
          - unity # <-- (Includes UNITY_SERIAL, UNITY_USERNAME, UNITY_PASSWORD)
        vars:
          UNITY_BIN: C:\Program Files\Unity\Hub\Editor\2020.3.23f1\Editor\Unity.exe
      scripts:
        - name: Activate License
          script: cmd.exe /c %UNITY_BIN% -batchmode -quit -logFile -serial %UNITY_SERIAL% -username %UNITY_USERNAME% -password %UNITY_PASSWORD%
        - name: Run Unit Tests
          script: cmd.exe /c %UNITY_BIN% -batchmode -executeMethod Runner.RunUnitTests -logFile -nographics -projectPath .
        - name: Build
          script: cmd.exe /c %UNITY_BIN% -batchmode -quit -logFile -projectPath . -executeMethod BuildScript.BuildWindows -nographics
      artifacts:
        - "Build/UnitTestingPong.exe"
      publishing:
        scripts:
          - name: Deactivate License
            script: cmd.exe /c %UNITY_BIN% -batchmode -quit -returnlicense -nographics
